import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Award, CalendarDays, Check, CheckCircle2, ChevronRight, ClipboardList, Plus, RefreshCw, Send, ShieldCheck, Users } from "lucide-react";

type Cycle = { id: string; name: string; periodStart: string; periodEnd: string; selfReviewDue: string; managerReviewDue: string; status: "open" | "closed"; totalReviews: number; completedReviews: number };
type Goal = { title: string; successMeasure: string; result: string; rating: number };
type Competency = { name: string; rating: number; comments: string };
type KpiScore = { kpiId: string; name: string; metric: string; target: string; weight: number; selfRating: number | null; selfResult: string | null; managerRating: number | null; managerComment: string | null; rating: number; evidence: string; comment: string };
type ReviewSection = { overallRating: number; summary: string; strengths: string; developmentPlan: string; recommendation: string; goals: Goal[]; competencies: Competency[]; kpiScores: KpiScore[] };
type Appraisal = { id: string; cycleId: string; cycleName: string; periodStart: string; periodEnd: string; selfReviewDue: string; managerReviewDue: string; cycleStatus: string; employeeId: string; employeeUserId: string; employeeName: string; jobTitle: string; department: string | null; reviewerUserId: string; reviewerName: string; status: "self_review" | "manager_review" | "acknowledgment" | "complete"; selfReviewJson: string | null; managerReviewJson: string | null; employeeAcknowledgment: string | null; employeeDecision: "accepted" | "declined" | null; decisionNote: string | null; managerRecommendation: string | null; updatedAt: string; kpis: Omit<KpiScore, "rating" | "evidence" | "comment">[] };
type Feedback = { overallRating: number; summary: string; strengths: string; improvements: string; recommendation: string; submittedAt: string };
type FeedbackTask = { id: string; relationship: string; status: string; cycleName: string; employeeName: string; jobTitle: string };
type Payload = { cycles: Cycle[]; appraisals: Appraisal[]; canManage: boolean };
type Props = { user: { id: string; permissions?: string[] }; onToast: (message: string) => void };

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { credentials: "include", ...init });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || "Request failed");
  return response.json() as Promise<T>;
}
const emptyReview = (): ReviewSection => ({ overallRating: 3, summary: "", strengths: "", developmentPlan: "", recommendation: "", goals: [{ title: "", successMeasure: "", result: "", rating: 3 }], competencies: [{ name: "Communication", rating: 3, comments: "" }, { name: "Collaboration", rating: 3, comments: "" }, { name: "Ownership and accountability", rating: 3, comments: "" }], kpiScores: [] });
const parseReview = (value: string | null): ReviewSection | null => { try { return value ? JSON.parse(value) as ReviewSection : null; } catch { return null; } };
const statusText = (review: Appraisal) => review.status === "complete" ? review.employeeDecision === "declined" ? "Declined by employee" : "Accepted by employee" : ({ self_review: "Self-review", manager_review: "Manager review", acknowledgment: "Employee decision", complete: "Complete" })[review.status];

export function Appraisals({ user, onToast }: Props) {
  const [data, setData] = useState<Payload>({ cycles: [], appraisals: [], canManage: false });
  const [employees, setEmployees] = useState<{ id: string; firstName: string; lastName: string; jobTitle: string }[]>([]);
  const [feedbackInbox, setFeedbackInbox] = useState<FeedbackTask[]>([]);
  const [feedbacks, setFeedbacks] = useState<Feedback[]>([]);
  const [feedbackCount, setFeedbackCount] = useState(0);
  const [selectedId, setSelectedId] = useState("");
  const [selectedFeedbackId, setSelectedFeedbackId] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<ReviewSection>(emptyReview);
  const [decisionNote, setDecisionNote] = useState("");
  const [showCycleForm, setShowCycleForm] = useState(false);
  const [cycleSaving, setCycleSaving] = useState(false);
  const [query, setQuery] = useState("");
  const selected = data.appraisals.find((review) => review.id === selectedId) || data.appraisals[0];
  const selfReview = parseReview(selected?.selfReviewJson || null);
  const managerReview = parseReview(selected?.managerReviewJson || null);
  const isSelf = selected?.employeeUserId === user.id;
  const isReviewer = selected?.reviewerUserId === user.id || data.canManage;
  const canSelfSubmit = Boolean(isSelf && user.permissions?.includes("appraisals.self.view") && selected?.status === "self_review" && selected.cycleStatus === "open");
  const canManagerSubmit = Boolean(isReviewer && selected?.status === "manager_review" && selected.cycleStatus === "open");
  const canDecide = Boolean(isSelf && user.permissions?.includes("appraisals.self.view") && selected?.status === "acknowledgment" && selected.cycleStatus === "open");
  const actionMode = canSelfSubmit ? "self-review" : canManagerSubmit ? "manager-review" : null;

  const load = async (resetSelection = false) => {
    try {
      const result = await api<Payload>("/api/appraisals");
      setData(result);
      if (resetSelection || !result.appraisals.some((item) => item.id === selectedId)) setSelectedId(result.appraisals[0]?.id || "");
      const [people, inbox] = await Promise.all([
        api<{ data: { id: string; firstName: string; lastName: string; jobTitle: string }[] }>("/api/employees").catch(() => ({ data: [] })),
        api<{ data: FeedbackTask[] }>("/api/appraisals/360-inbox").catch(() => ({ data: [] })),
      ]);
      setEmployees(people.data);
      setFeedbackInbox(inbox.data);
    } catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not load appraisals"); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(true); }, []);
  useEffect(() => {
    if (!selected) return;
    const saved = canManagerSubmit ? null : selfReview;
    const initial = saved || emptyReview();
    initial.kpiScores = selected.kpis.map((kpi) => ({ ...kpi, rating: canManagerSubmit ? 3 : kpi.selfRating || 3, evidence: kpi.selfResult || "", comment: "" }));
    if (canManagerSubmit) {
      initial.goals = selfReview?.goals?.length ? selfReview.goals.map((goal) => ({ ...goal, rating: 3 })) : initial.goals;
      initial.competencies = selfReview?.competencies?.length ? selfReview.competencies.map((item) => ({ ...item, rating: 3, comments: "" })) : initial.competencies;
    }
    setForm(initial);
    setDecisionNote("");
  }, [selected?.id, selected?.status]);
  useEffect(() => {
    if (!selected) return;
    void api<{ submittedCount: number; feedback: Feedback[] }>(`/api/appraisals/${selected.id}/360-feedback`).then((result) => { setFeedbacks(result.feedback); setFeedbackCount(result.submittedCount); }).catch(() => { setFeedbacks([]); setFeedbackCount(0); });
  }, [selected?.id, selected?.updatedAt]);

  const filtered = useMemo(() => data.appraisals.filter((item) => `${item.employeeName} ${item.cycleName} ${item.jobTitle} ${item.department || ""}`.toLowerCase().includes(query.toLowerCase())), [data.appraisals, query]);
  const submitReview = async (event: FormEvent) => {
    event.preventDefault(); if (!selected || !actionMode) return;
    setSaving(true);
    try {
      await api(`/api/appraisals/${selected.id}/${actionMode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) });
      onToast(actionMode === "self-review" ? "Self-review submitted to your reviewer" : "Manager assessment sent for employee decision"); await load();
    } catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not submit review"); }
    finally { setSaving(false); }
  };
  const createCycle = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const cycleForm = event.currentTarget; const body = Object.fromEntries(new FormData(cycleForm).entries()); setCycleSaving(true);
    try { const result = await api<{ assignedCount: number }>("/api/appraisal-cycles", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); onToast(`Appraisal cycle launched for ${result.assignedCount} active employees`); cycleForm.reset(); setShowCycleForm(false); await load(true); }
    catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not create appraisal cycle"); } finally { setCycleSaving(false); }
  };
  const closeCycle = async (cycle: Cycle) => { try { await api(`/api/appraisal-cycles/${cycle.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: "closed" }) }); onToast(`${cycle.name} is now closed`); await load(); } catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not close cycle"); } };
  const decide = async (decision: "accepted" | "declined") => {
    if (!selected || decisionNote.trim().length < 3) { onToast("Please add a note before submitting your decision."); return; }
    setSaving(true);
    try { await api(`/api/appraisals/${selected.id}/decision`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, note: decisionNote }) }); onToast(decision === "accepted" ? "Appraisal accepted" : "Appraisal declined; your note was sent to HR and the reviewer"); await load(); }
    catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not record your decision"); } finally { setSaving(false); }
  };
  const nominate = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!selected) return; const formEl = event.currentTarget; const ids = Array.from(formEl.querySelectorAll<HTMLInputElement>("input[name=respondent]:checked")).map((input) => input.value);
    const relationship = (new FormData(formEl).get("relationship") || "peer").toString();
    try { const result = await api<{ invitedCount: number }>(`/api/appraisals/${selected.id}/360-invitations`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ respondents: ids.map((employeeId) => ({ employeeId, relationship })) }) }); onToast(`${result.invitedCount} confidential 360 feedback requests sent`); await load(); }
    catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not invite reviewers"); }
  };
  const submit360 = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const feedbackForm = event.currentTarget; const body = Object.fromEntries(new FormData(feedbackForm).entries()); if (!selectedFeedbackId) return; setSaving(true);
    try { await api(`/api/appraisal-360/${selectedFeedbackId}/submit`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); onToast("Confidential 360 feedback submitted"); setSelectedFeedbackId(""); await load(); }
    catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not submit feedback"); } finally { setSaving(false); }
  };
  const setGoal = (index: number, key: keyof Goal, value: string | number) => setForm((current) => ({ ...current, goals: current.goals.map((goal, i) => i === index ? { ...goal, [key]: value } : goal) }));
  const setCompetency = (index: number, key: keyof Competency, value: string | number) => setForm((current) => ({ ...current, competencies: current.competencies.map((item, i) => i === index ? { ...item, [key]: value } : item) }));
  const setKpi = (index: number, key: "rating" | "evidence" | "comment", value: string | number) => setForm((current) => ({ ...current, kpiScores: current.kpiScores.map((item, i) => i === index ? { ...item, [key]: value } : item) }));

  return <section className="page-section appraisal-page">
    <div className="page-heading"><div><div className="eyebrow">PEOPLE · PERFORMANCE</div><h1>Performance appraisals</h1><p>Employee, manager and confidential 360 feedback with goals, KPI scoring, recommendations and employee decision.</p></div><div className="appraisal-heading-actions"><button className="secondary-button" onClick={() => void load()}><RefreshCw size={15} /> Refresh</button>{data.canManage && <button className="primary-button" onClick={() => setShowCycleForm((value) => !value)}><Plus size={16} /> New review cycle</button>}</div></div>
    {showCycleForm && <form className="card appraisal-cycle-form" onSubmit={createCycle}><div className="card-heading"><div><h2>Set up a review cycle</h2><p>Active employees are enrolled. Existing KPI definitions attach automatically. Line managers review their direct reports; HR is the fallback when none is assigned.</p></div></div><label>Cycle name<input name="name" required maxLength={120} placeholder="e.g. 2026 Mid-year Performance Review" /></label><div className="appraisal-date-grid"><label>Review period starts<input type="date" name="periodStart" required /></label><label>Review period ends<input type="date" name="periodEnd" required /></label><label>Employee self-review deadline<input type="date" name="selfReviewDue" required /></label><label>Manager review deadline<input type="date" name="managerReviewDue" required /></label></div><div className="appraisal-form-actions"><button type="button" className="secondary-button" onClick={() => setShowCycleForm(false)}>Cancel</button><button className="primary-button" disabled={cycleSaving}>{cycleSaving ? "Launching…" : "Launch cycle"}</button></div></form>}
    <div className="appraisal-overview-grid"><div className="card appraisal-overview"><span className="appraisal-overview-icon"><CalendarDays size={17} /></span><span>Review cycles</span><strong>{data.cycles.length}</strong><small>Organization-wide cycles</small></div><div className="card appraisal-overview"><span className="appraisal-overview-icon green"><CheckCircle2 size={17} /></span><span>Completed decisions</span><strong>{data.appraisals.filter((item) => item.status === "complete").length}</strong><small>Employee accepted or declined</small></div><div className="card appraisal-overview"><span className="appraisal-overview-icon violet"><Users size={17} /></span><span>My manager queue</span><strong>{data.appraisals.filter((item) => item.reviewerUserId === user.id && item.status === "manager_review").length}</strong><small>Waiting for manager feedback</small></div></div>
    {data.canManage && <section className="card appraisal-cycles"><div className="card-heading"><div><h2>Review cycles</h2><p>Track deadlines and completion across the organization.</p></div></div>{data.cycles.length ? <div className="appraisal-cycle-list">{data.cycles.map((cycle) => <div className="appraisal-cycle-row" key={cycle.id}><div className="appraisal-cycle-mark"><Award size={17} /></div><div className="appraisal-cycle-copy"><strong>{cycle.name}</strong><span>{cycle.periodStart} – {cycle.periodEnd} · Self due {cycle.selfReviewDue} · Manager due {cycle.managerReviewDue}</span></div><div className="appraisal-cycle-progress"><strong>{cycle.completedReviews || 0}<small> / {cycle.totalReviews}</small></strong><span>decisions</span></div><span className={`appraisal-status ${cycle.status}`}>{cycle.status}</span>{cycle.status === "open" && <button className="secondary-button compact" onClick={() => void closeCycle(cycle)}>Close cycle</button>}</div>)}</div> : <div className="appraisal-empty"><ClipboardList size={22} /><span>No cycles yet. Create a cycle to assign performance reviews.</span></div>}</section>}
    <div className="appraisal-workspace">
      <section className="card appraisal-queue"><div className="card-heading"><div><h2>{data.canManage ? "Assigned reviews" : "My reviews"}</h2><p>Employee self-review and manager-review tasks.</p></div></div><div className="appraisal-search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reviews" /></div><div className="appraisal-list">{loading ? <div className="appraisal-empty">Loading appraisal records…</div> : filtered.length ? filtered.map((item) => <button key={item.id} className={`appraisal-list-item ${selected?.id === item.id ? "active" : ""}`} onClick={() => { setSelectedId(item.id); setSelectedFeedbackId(""); }}><span className="appraisal-person-avatar">{item.employeeName.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</span><span className="appraisal-person-copy"><strong>{item.employeeName}</strong><small>{item.jobTitle} · {item.cycleName}</small><span className={`appraisal-status ${item.status}`}>{statusText(item)}</span></span><ChevronRight size={16} /></button>) : <div className="appraisal-empty"><ClipboardList size={21} /><span>No appraisal records are assigned to you yet.</span></div>}</div>
        <div className="appraisal-360-inbox"><h3>360 feedback requests</h3>{feedbackInbox.map((task) => <button key={task.id} className="appraisal-inbox-task" onClick={() => setSelectedFeedbackId(task.id)}><span><strong>{task.employeeName}</strong><small>{task.cycleName} · {task.relationship}</small></span><span className={`appraisal-status ${task.status}`}>{task.status === "assigned" ? "Respond" : "Submitted"}</span></button>)}{!feedbackInbox.length && <small>No 360 requests.</small>}</div>
      </section>
      <section className="card appraisal-detail">{selectedFeedbackId ? <><div className="appraisal-detail-heading"><div><div className="eyebrow">CONFIDENTIAL · 360 FEEDBACK</div><h2>Your feedback</h2><p>Your response is anonymous to the employee and appraisal reviewer.</p></div></div><form className="appraisal-review-form" onSubmit={submit360}><label>Overall rating<select name="overallRating" defaultValue="3">{[1,2,3,4,5].map((rating) => <option key={rating}>{rating}</option>)}</select></label><label>Observed impact and examples<textarea name="summary" rows={3} required minLength={5} /></label><label>Strengths<textarea name="strengths" rows={2} /></label><label>Growth opportunities<textarea name="improvements" rows={2} /></label><label>Recommendation<textarea name="recommendation" rows={2} placeholder="Practical support or next steps" /></label><button className="primary-button" disabled={saving}><Send size={15} /> Submit confidential feedback</button></form></> : selected ? <><div className="appraisal-detail-heading"><div><div className="eyebrow">{selected.cycleName}</div><h2>{selected.employeeName}</h2><p>{selected.jobTitle}{selected.department ? ` · ${selected.department}` : ""} · Reviewer: {selected.reviewerName}</p></div><span className={`appraisal-status ${selected.status}`}>{statusText(selected)}</span></div><div className="appraisal-deadlines"><span>Period <strong>{selected.periodStart} — {selected.periodEnd}</strong></span><span>Self due <strong>{selected.selfReviewDue}</strong></span><span>Manager due <strong>{selected.managerReviewDue}</strong></span></div>
        {actionMode && <form className="appraisal-review-form" onSubmit={submitReview}>{actionMode === "manager-review" && selfReview && <ReviewSummary title="Employee self-review" review={selfReview} />}<div className="appraisal-form-title"><h3>{actionMode === "self-review" ? "Your self-review" : "Manager assessment"}</h3><span>Rate from 1 (needs improvement) to 5 (exceptional)</span></div><label>Overall performance rating<select value={form.overallRating} onChange={(event) => setForm({ ...form, overallRating: Number(event.target.value) })}>{[1,2,3,4,5].map((rating) => <option key={rating} value={rating}>{rating} — {(["Needs improvement","Developing","Meets expectations","Exceeds expectations","Exceptional"] as const)[rating - 1]}</option>)}</select></label>
          {form.kpiScores.length > 0 && <div className="appraisal-kpi-ratings"><div><strong>Assigned KPIs</strong><small>Targets are set by HR. Rate performance and include evidence for every KPI.</small></div>{form.kpiScores.map((kpi, index) => <div className="appraisal-kpi-row" key={kpi.kpiId}><span><b>{kpi.name}</b><small>{kpi.metric} · Target: {kpi.target} · Weight {kpi.weight}%</small>{actionMode === "manager-review" && <small>Employee self-rating: {kpi.selfRating ?? "—"}/5{kpi.selfResult ? ` · ${kpi.selfResult}` : ""}</small>}</span><label>Rating<select value={kpi.rating} onChange={(event) => setKpi(index, "rating", Number(event.target.value))}>{[1,2,3,4,5].map((rating) => <option key={rating}>{rating}</option>)}</select></label><label>{actionMode === "self-review" ? "Evidence" : "Manager comment"}<textarea required value={actionMode === "self-review" ? kpi.evidence : kpi.comment} onChange={(event) => setKpi(index, actionMode === "self-review" ? "evidence" : "comment", event.target.value)} rows={2} /></label></div>)}</div>}
          <label>{actionMode === "self-review" ? "Performance summary" : "Manager feedback"}<textarea required value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })} rows={3} maxLength={4000} /></label><label>Strengths<textarea value={form.strengths} onChange={(event) => setForm({ ...form, strengths: event.target.value })} rows={2} maxLength={4000} /></label>
          <div className="appraisal-section-label"><div><strong>Goals and outcomes</strong><span>Set expectations, evidence and ratings.</span></div><button type="button" className="text-button" onClick={() => setForm((current) => ({ ...current, goals: [...current.goals, { title: "", successMeasure: "", result: "", rating: 3 }] }))}><Plus size={14} /> Add goal</button></div>{form.goals.map((goal, index) => <div className="appraisal-entry" key={`goal-${index}`}><label>Goal<input required value={goal.title} onChange={(event) => setGoal(index, "title", event.target.value)} /></label><label>Success measure<input required value={goal.successMeasure} onChange={(event) => setGoal(index, "successMeasure", event.target.value)} /></label><label>Result / evidence<textarea value={goal.result} onChange={(event) => setGoal(index, "result", event.target.value)} rows={2} /></label><label>Rating<select value={goal.rating} onChange={(event) => setGoal(index, "rating", Number(event.target.value))}>{[1,2,3,4,5].map((rating) => <option key={rating}>{rating}</option>)}</select></label>{form.goals.length > 1 && <button type="button" className="text-button danger" onClick={() => setForm((current) => ({ ...current, goals: current.goals.filter((_, i) => i !== index) }))}>Remove</button>}</div>)}
          <div className="appraisal-section-label"><div><strong>Core competencies</strong><span>Rate behaviours and attach evidence.</span></div><button type="button" className="text-button" onClick={() => setForm((current) => ({ ...current, competencies: [...current.competencies, { name: "", rating: 3, comments: "" }] }))}><Plus size={14} /> Add competency</button></div>{form.competencies.map((item, index) => <div className="appraisal-entry competency" key={`competency-${index}`}><label>Competency<input required value={item.name} onChange={(event) => setCompetency(index, "name", event.target.value)} /></label><label>Rating<select value={item.rating} onChange={(event) => setCompetency(index, "rating", Number(event.target.value))}>{[1,2,3,4,5].map((rating) => <option key={rating}>{rating}</option>)}</select></label><label>Evidence / comments<textarea value={item.comments} onChange={(event) => setCompetency(index, "comments", event.target.value)} rows={2} /></label>{form.competencies.length > 1 && <button type="button" className="text-button danger" onClick={() => setForm((current) => ({ ...current, competencies: current.competencies.filter((_, i) => i !== index) }))}>Remove</button>}</div>)}
          <label>Development plan<textarea value={form.developmentPlan} onChange={(event) => setForm({ ...form, developmentPlan: event.target.value })} rows={3} maxLength={4000} /></label>{actionMode === "manager-review" && <label>Manager recommendation<textarea value={form.recommendation} onChange={(event) => setForm({ ...form, recommendation: event.target.value })} rows={3} placeholder="Promotion, role development, training, recognition or support recommendation" /></label>}
          <div className="appraisal-form-actions"><span><ShieldCheck size={15} /> Saved to the employee’s confidential HR record.</span><button className="primary-button" disabled={saving}><Send size={15} />{saving ? "Submitting…" : actionMode === "self-review" ? "Submit self-review" : "Submit manager review"}</button></div></form>}
        {!actionMode && <div className="appraisal-readonly">{selfReview && <ReviewSummary title="Employee self-review" review={selfReview} />}{managerReview && <ReviewSummary title="Manager assessment" review={managerReview} recommendation={selected.managerRecommendation || managerReview.recommendation} />}
          {selected.status === "self_review" && (canSelfSubmit || data.canManage) && <><h3>Confidential 360 feedback</h3><p>{feedbackCount < 3 ? `${feedbackCount} response(s) received. Feedback stays hidden from the employee until at least 3 colleagues respond.` : `${feedbackCount} anonymous responses are ready for review.`}</p>{feedbacks.map((feedback, index) => <ReviewSummary key={index} title={`Anonymous response ${index + 1}`} review={{ ...emptyReview(), overallRating: feedback.overallRating, summary: feedback.summary, strengths: feedback.strengths, developmentPlan: feedback.improvements, recommendation: feedback.recommendation }} />)}</>}
          {canSelfSubmit && <details className="appraisal-ack-form"><summary><strong>Nominate confidential 360 reviewers</strong></summary><p>Select colleagues who have worked with you this cycle. You may nominate up to eight.</p><form onSubmit={nominate}><label>Relationship<select name="relationship"><option value="peer">Peer</option><option value="direct_report">Direct report</option><option value="cross_functional">Cross-functional partner</option></select></label><div className="appraisal-nominee-list">{employees.filter((person) => person.id !== selected.employeeId).map((person) => <label key={person.id}><input type="checkbox" name="respondent" value={person.id} /><span>{person.firstName} {person.lastName}<small>{person.jobTitle}</small></span></label>)}</div><button className="secondary-button" type="submit">Request 360 feedback</button></form></details>}
          {canDecide && <form className="appraisal-ack-form" onSubmit={(event) => event.preventDefault()}><h3>Your decision: accept or decline</h3><p>Your response is recorded and shared with HR and your reviewer. Add any comments or disagreement before choosing.</p><textarea required minLength={3} maxLength={2000} value={decisionNote} onChange={(event) => setDecisionNote(event.target.value)} rows={3} placeholder="Comments, questions or areas of disagreement…" /><div className="appraisal-decision-actions"><button type="button" className="primary-button" disabled={saving} onClick={() => void decide("accepted")}><Check size={15} /> Accept appraisal</button><button type="button" className="secondary-button decline" disabled={saving} onClick={() => void decide("declined")}>Decline appraisal</button></div></form>}
          {selected.status === "complete" && <div className="appraisal-complete-note"><CheckCircle2 size={18} /><span>Employee {selected.employeeDecision || "accepted"} the appraisal{selected.decisionNote ? `: “${selected.decisionNote}”` : ""}.</span></div>}
          {!selfReview && !managerReview && selected.status === "self_review" && !canSelfSubmit && <div className="appraisal-empty">Waiting for the employee to submit their self-review.</div>}{selected.status === "manager_review" && !canManagerSubmit && <div className="appraisal-empty">Waiting for the assigned reviewer to complete the manager assessment.</div>}</div>}
      </> : <div className="appraisal-empty large"><Award size={28} /><strong>No review selected</strong><span>Create a cycle or wait for a review assignment.</span></div>}</section>
    </div>
  </section>;
}

function ReviewSummary({ title, review, recommendation }: { title: string; review: ReviewSection; recommendation?: string | null }) {
  return <section className="appraisal-summary"><div className="appraisal-summary-heading"><h3>{title}</h3><span>Overall rating <strong>{review.overallRating} / 5</strong></span></div><p>{review.summary}</p>{review.strengths && <div className="appraisal-summary-text"><strong>Strengths</strong><span>{review.strengths}</span></div>}{review.developmentPlan && <div className="appraisal-summary-text"><strong>Development plan</strong><span>{review.developmentPlan}</span></div>}{recommendation && <div className="appraisal-summary-text"><strong>Recommendation</strong><span>{recommendation}</span></div>}{review.kpiScores?.length > 0 && <div className="appraisal-summary-table"><strong>KPI ratings</strong>{review.kpiScores.map((kpi, index) => <div key={kpi.kpiId || index}><span><b>{kpi.name}</b><small>{kpi.metric} · target {kpi.target}{kpi.evidence || kpi.comment ? ` · ${kpi.evidence || kpi.comment}` : ""}</small></span><em>{kpi.rating}/5</em></div>)}</div>}{review.goals?.length > 0 && <div className="appraisal-summary-table"><strong>Goals and outcomes</strong>{review.goals.map((goal, index) => <div key={index}><span><b>{goal.title}</b><small>{goal.successMeasure}{goal.result ? ` · ${goal.result}` : ""}</small></span><em>{goal.rating}/5</em></div>)}</div>}{review.competencies?.length > 0 && <div className="appraisal-summary-table"><strong>Competencies</strong>{review.competencies.map((item, index) => <div key={index}><span><b>{item.name}</b><small>{item.comments || "No comment."}</small></span><em>{item.rating}/5</em></div>)}</div>}</section>;
}
