import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import {
  AlertCircle, ArrowUpRight, BriefcaseBusiness, CalendarDays, Check, ChevronDown, CircleDollarSign,
  Clock3, FileCheck2, FileText, Filter, Headphones, Laptop, LifeBuoy, Mail, MapPin, MoreHorizontal,
  Package, Plus, Search, ShieldCheck, TicketCheck, UserRound, Users, WalletCards, Wrench, X,
} from "lucide-react";
import { demoAssets, demoCustomers, demoEvents, demoExpenses, demoRequests, demoTickets, demoVendors } from "./data/demo";
import type { ApprovalRequest, Asset, CalendarEvent, Customer, Expense, PageId, SupportTicket, Vendor } from "./types";

type OpsProps = { page: PageId; role: string; onToast: (message: string) => void };
type OpsModal = "expense" | "request" | "asset" | "vendor" | "ticket" | "customer" | null;

async function opsApi<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { credentials: "include", ...init });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || "Request failed");
  return response.json() as Promise<T>;
}

const naira = (value: number) => `₦${new Intl.NumberFormat("en-NG", { maximumFractionDigits: 0 }).format(value)}`;
const compactNaira = (value: number) => `₦${new Intl.NumberFormat("en-NG", { notation: "compact", maximumFractionDigits: 1 }).format(value)}`;
const titleCase = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (match) => match.toUpperCase());
const isFinancialRequest = (request: ApprovalRequest) => (typeof request.amount === "number" && Number.isFinite(request.amount)) || ["expense", "purchase", "budget", "payroll", "reimbursement", "payment", "financial", "asset purchase"].includes(request.requestType.trim().toLowerCase());

function OpsHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) {
  return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action && <div className="page-header-action">{action}</div>}</div>;
}

function OpsCardHeading({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) {
  return <div className="card-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>;
}

function OpsStat({ icon: Icon, tone, label, value, detail }: { icon: typeof WalletCards; tone: string; label: string; value: string; detail: string }) {
  return <div className="card ops-stat"><span className={`ops-stat-icon ${tone}`}><Icon size={17} /></span><span className="ops-stat-label">{label}</span><strong>{value}</strong><small>{detail}</small></div>;
}

function Status({ value }: { value: string }) {
  return <span className={`status-badge ${value.toLowerCase().replace(/ /g, "_")}`}>{titleCase(value)}</span>;
}

function OpsTableToolbar({ placeholder, onSearch, action }: { placeholder: string; onSearch?: (value: string) => void; action?: ReactNode }) {
  return <div className="table-toolbar"><div className="table-search"><Search size={16} /><input placeholder={placeholder} onChange={(event) => onSearch?.(event.target.value)} /></div><div className="toolbar-actions">{action || <button className="filter-button"><Filter size={14} /> Filters <ChevronDown size={14} /></button>}</div></div>;
}

export function OperationalWorkspace({ page, role, onToast }: OpsProps) {
  const [expenses, setExpenses] = useState<Expense[]>(demoExpenses);
  const [requests, setRequests] = useState<ApprovalRequest[]>(demoRequests);
  const [assets, setAssets] = useState<Asset[]>(demoAssets);
  const [vendors, setVendors] = useState<Vendor[]>(demoVendors);
  const [tickets, setTickets] = useState<SupportTicket[]>(demoTickets);
  const [events, setEvents] = useState<CalendarEvent[]>(demoEvents);
  const [customers, setCustomers] = useState<Customer[]>(demoCustomers);
  const [modal, setModal] = useState<OpsModal>(null);

  useEffect(() => {
    const load = async () => {
      try {
        const [expenseData, requestData, assetData, vendorData, ticketData, eventData, customerData] = await Promise.all([
          opsApi<{ data: Expense[] }>("/api/expenses"), opsApi<{ data: ApprovalRequest[] }>("/api/requests"), opsApi<{ data: Asset[] }>("/api/assets"), opsApi<{ data: Vendor[] }>("/api/vendors"), opsApi<{ data: SupportTicket[] }>("/api/tickets"), opsApi<{ data: CalendarEvent[] }>("/api/calendar"), opsApi<{ data: Customer[] }>("/api/customers"),
        ]);
        setExpenses(expenseData.data); setRequests(requestData.data); setAssets(assetData.data); setVendors(vendorData.data); setTickets(ticketData.data); setEvents(eventData.data); setCustomers(customerData.data);
      } catch {
        // The seeded collections keep the workspace useful in Vite-only demo mode.
      }
    };
    void load();
  }, []);

  const createExpense = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries());
    const amount = Number(values.amount);
    const local: Expense = { id: `local-${Date.now()}`, employee: "Amaka Okafor", category: String(values.category), amount, currency: "NGN", expenseDate: new Date(String(values.expenseDate)).toLocaleDateString("en-NG", { day: "2-digit", month: "short", year: "numeric" }), description: String(values.description), status: "submitted" };
    try { const saved = await opsApi<{ id: string; employee: string }>("/api/expenses", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); local.id = saved.id; local.employee = saved.employee; }
    catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not submit expense"); return; }
    setExpenses((current) => [local, ...current]); setRequests((current) => [{ id: `local-request-${Date.now()}`, requestType: "Expense", title: local.description, requester: local.employee, amount, status: "pending", requiredRole: "CEO", createdAt: "Just now" }, ...current]); setModal(null); onToast("Expense submitted for CEO approval");
  };

  const createRequest = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries());
    try {
      const saved = await opsApi<{ id: string; requiredRole: string; status: "pending" }>("/api/requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) });
      const amount = values.amount ? Number(values.amount) : undefined;
      setRequests((current) => [{ id: saved.id, requestType: String(values.requestType), title: String(values.title), requester: "You", amount, status: saved.status, requiredRole: saved.requiredRole, createdAt: "Just now" }, ...current]);
      setModal(null); onToast(`Request submitted. ${saved.requiredRole} has been notified by email and in-app.`);
    } catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not submit request"); }
  };

  const reviewRequest = async (item: ApprovalRequest, status: "approved" | "rejected") => {
    const reason = status === "rejected" ? window.prompt("Give the requester a clear reason for rejecting this request:")?.trim() : "";
    if (status === "rejected" && !reason) { if (reason !== null) onToast("A rejection reason is required."); return; }
    try {
      const result = await opsApi<{ status: "approved" | "rejected" | "pending"; requiredRole?: string }>(`/api/requests/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status, reason }) });
      setRequests((current) => current.map((request) => request.id === item.id ? { ...request, status: result.status, requiredRole: result.requiredRole || request.requiredRole } : request));
      if (item.requestType === "Expense" && result.status !== "pending") setExpenses((current) => current.map((expense) => expense.description === item.title ? { ...expense, status: result.status as Expense["status"] } : expense));
      onToast(result.status === "pending" ? `Request sent to ${result.requiredRole || item.requiredRole} for approval.` : `Request ${status}`);
    } catch (cause) { onToast(cause instanceof Error ? cause.message : "Could not process approval"); }
  };

  const createAsset = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const item: Asset = { id: `local-${Date.now()}`, assetTag: "AST-PENDING", name: String(values.name), category: String(values.category), serialNumber: String(values.serialNumber || "—"), status: "available", location: String(values.location || "Unassigned"), value: Number(values.value || 0) };
    try { const saved = await opsApi<{ id: string; assetTag: string }>("/api/assets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); item.id = saved.id; item.assetTag = saved.assetTag; } catch { /* demo mode */ }
    setAssets((current) => [item, ...current]); setModal(null); onToast("Asset added to the register");
  };

  const createVendor = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const item: Vendor = { id: `local-${Date.now()}`, name: String(values.name), category: String(values.category), contactName: String(values.contactName), email: String(values.email), status: "review", contractEnd: String(values.contractEnd || "Not set"), spend: 0 };
    try { const saved = await opsApi<{ id: string }>("/api/vendors", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); item.id = saved.id; } catch { /* demo mode */ }
    setVendors((current) => [item, ...current]); setModal(null); onToast("Vendor added for review");
  };

  const createTicket = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const item: SupportTicket = { id: `local-${Date.now()}`, ticketNumber: "ZD-PENDING", subject: String(values.subject), category: String(values.category), priority: String(values.priority) as SupportTicket["priority"], status: "open", requester: "Amaka Okafor", createdAt: "Just now" };
    try { const saved = await opsApi<{ id: string; ticketNumber: string }>("/api/tickets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); item.id = saved.id; item.ticketNumber = saved.ticketNumber; } catch { /* demo mode */ }
    setTickets((current) => [item, ...current]); setModal(null); onToast("Support ticket created");
  };

  const createCustomer = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const item: Customer = { id: `local-${Date.now()}`, name: String(values.name), company: String(values.company), email: String(values.email), stage: String(values.stage) as Customer["stage"], value: Number(values.value || 0), owner: "Amaka Okafor", lastActivity: "Just now" };
    try { const saved = await opsApi<{ id: string }>("/api/customers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); item.id = saved.id; } catch { /* demo mode */ }
    setCustomers((current) => [item, ...current]); setModal(null); onToast("Customer added to the pipeline");
  };

  const shared = { expenses, requests, assets, vendors, tickets, events, customers, role, onToast, openModal: setModal, reviewRequest };
  return <>{page === "expenses" && <ExpensesPage {...shared} />}{page === "requests" && <RequestsPage {...shared} />}{page === "assets" && <AssetsPage {...shared} />}{page === "vendors" && <VendorsPage {...shared} />}{page === "helpdesk" && <HelpdeskPage {...shared} />}{page === "calendar" && <CalendarPage {...shared} />}{page === "customers" && <CustomersPage {...shared} />}{page === "budgets" && <BudgetsPage onToast={onToast} />}
    {modal === "expense" && <OpsModal title="Submit expense" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createExpense}><div className="form-grid"><label>Category<select name="category" defaultValue="Software"><option>Software</option><option>Travel</option><option>Operations</option><option>Client entertainment</option><option>Learning</option></select></label><label>Amount (NGN)<input name="amount" type="number" min="1" required placeholder="150000" /></label></div><label>Expense date<input name="expenseDate" type="date" required defaultValue="2026-09-28" /></label><label>Description<textarea name="description" required placeholder="What was this expense for?" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setModal(null)}>Cancel</button><button className="button primary"><WalletCards size={16} /> Submit claim</button></div></form></OpsModal>}
    {modal === "request" && <OpsModal title="New operational request" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createRequest}><div className="form-grid"><label>Request type<select name="requestType" defaultValue="Operational"><option>Operational</option><option>Access</option><option>HR</option><option>Leave</option><option>Purchase</option><option>Budget</option><option>Other</option></select></label><label>Approver for non-financial requests<select name="approverRole" defaultValue="Manager"><option>Manager</option><option>HR Admin</option><option>CEO</option></select></label></div><label>Request title<input name="title" required maxLength={120} placeholder="What do you need approved?" /></label><label>Details<textarea name="details" required maxLength={2000} placeholder="Add the context the approver needs." /></label><label>Amount (NGN) <small>Optional; any amount routes to the CEO</small><input name="amount" type="number" min="0.01" step="0.01" placeholder="Leave blank if not financial" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setModal(null)}>Cancel</button><button className="button primary"><FileCheck2 size={16} /> Submit for approval</button></div></form></OpsModal>}
    {modal === "asset" && <OpsModal title="Add asset" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createAsset}><div className="form-grid"><label>Asset name<input name="name" required placeholder="MacBook Pro" /></label><label>Category<select name="category" defaultValue="Laptop"><option>Laptop</option><option>Mobile</option><option>Equipment</option><option>Vehicle</option><option>Software license</option></select></label></div><div className="form-grid"><label>Serial number<input name="serialNumber" placeholder="Serial / licence ID" /></label><label>Value (NGN)<input name="value" type="number" min="0" placeholder="500000" /></label></div><label>Location<input name="location" placeholder="Lagos office" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setModal(null)}>Cancel</button><button className="button primary"><Package size={16} /> Add asset</button></div></form></OpsModal>}
    {modal === "vendor" && <OpsModal title="Add vendor" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createVendor}><div className="form-grid"><label>Company name<input name="name" required placeholder="Vendor company" /></label><label>Category<select name="category" defaultValue="Technology"><option>Technology</option><option>Facilities</option><option>Professional services</option><option>Logistics</option></select></label></div><div className="form-grid"><label>Contact name<input name="contactName" placeholder="Contact person" /></label><label>Email<input name="email" type="email" placeholder="vendor@example.com" /></label></div><label>Contract end<input name="contractEnd" type="date" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setModal(null)}>Cancel</button><button className="button primary"><BriefcaseBusiness size={16} /> Add vendor</button></div></form></OpsModal>}
    {modal === "ticket" && <OpsModal title="Create support ticket" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createTicket}><label>Subject<input name="subject" required placeholder="What do you need help with?" /></label><div className="form-grid"><label>Category<select name="category" defaultValue="IT"><option>IT</option><option>HR</option><option>Finance</option><option>Facilities</option><option>Other</option></select></label><label>Priority<select name="priority" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>urgent</option></select></label></div><label>Description<textarea name="description" placeholder="Add useful context for the support team" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setModal(null)}>Cancel</button><button className="button primary"><LifeBuoy size={16} /> Create ticket</button></div></form></OpsModal>}
    {modal === "customer" && <OpsModal title="Add customer" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createCustomer}><div className="form-grid"><label>Contact name<input name="name" required placeholder="Customer contact" /></label><label>Company<input name="company" placeholder="Company name" /></label></div><div className="form-grid"><label>Email<input name="email" type="email" required placeholder="customer@example.com" /></label><label>Deal value (NGN)<input name="value" type="number" min="0" placeholder="1000000" /></label></div><label>Pipeline stage<select name="stage" defaultValue="lead"><option value="lead">Lead</option><option value="qualified">Qualified</option><option value="proposal">Proposal</option><option value="negotiation">Negotiation</option></select></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setModal(null)}>Cancel</button><button className="button primary"><Users size={16} /> Add customer</button></div></form></OpsModal>}
  </>;
}

type SharedProps = { expenses: Expense[]; requests: ApprovalRequest[]; assets: Asset[]; vendors: Vendor[]; tickets: SupportTicket[]; events: CalendarEvent[]; customers: Customer[]; role: string; onToast: (message: string) => void; openModal: (modal: Exclude<OpsModal, null>) => void; reviewRequest: (request: ApprovalRequest, status: "approved" | "rejected") => void };

function ExpensesPage({ expenses, onToast, openModal }: SharedProps) {
  const [query, setQuery] = useState(""); const filtered = useMemo(() => expenses.filter((item) => `${item.employee} ${item.category} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [expenses, query]); const total = expenses.reduce((sum, item) => sum + item.amount, 0); const pending = expenses.filter((item) => item.status === "submitted").reduce((sum, item) => sum + item.amount, 0);
  return <><OpsHeader eyebrow="FINANCE / EXPENSES" title="Expenses" description="Submit, review and pay expenses with a clear approval trail." action={<button className="button primary" onClick={() => openModal("expense")}><Plus size={16} /> Submit expense</button>} /><div className="ops-stat-grid"><OpsStat icon={CircleDollarSign} tone="blue" label="Total this month" value={compactNaira(total || 18450000)} detail="Across all categories" /><OpsStat icon={Clock3} tone="orange" label="Awaiting approval" value={compactNaira(pending || 605000)} detail="Needs finance review" /><OpsStat icon={Check} tone="green" label="Approved claims" value={`${expenses.filter((item) => item.status === "approved" || item.status === "paid").length + 68}`} detail="This month" /><OpsStat icon={ShieldCheck} tone="violet" label="Policy compliance" value="94%" detail="Within spend limits" /></div><section className="card table-card"><div className="ops-table-heading"><div><OpsCardHeading title="Expense register" subtitle="Every claim is linked to a request and audit history." /></div><div className="expense-policy"><ShieldCheck size={14} /> Policy checks on</div></div><OpsTableToolbar placeholder="Search employee, category or description" onSearch={setQuery} action={<><button className="filter-button"><Filter size={14} /> All statuses <ChevronDown size={14} /></button><button className="filter-button" onClick={() => onToast("CSV export prepared")}><FileText size={14} /> Export</button></>} /><div className="table-scroll"><table><thead><tr><th>Claim</th><th>Category</th><th>Date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><div className="employee-cell"><div className="avatar avatar-small">{item.employee.split(" ").map((word) => word[0]).join("")}</div><div><strong>{item.description}</strong><span>{item.employee}{item.project ? ` · ${item.project}` : ""}</span></div></div></td><td>{item.category}</td><td>{item.expenseDate}</td><td><strong>{naira(item.amount)}</strong></td><td><Status value={item.status} /></td><td><button className="text-button" onClick={() => onToast(`Opened claim ${item.id}`)}>View</button></td></tr>)}</tbody></table></div></section></>;
}

function RequestsPage({ requests, role, onToast, openModal, reviewRequest }: SharedProps) {
  const pending = requests.filter((item) => item.status === "pending");
  return <>
    <OpsHeader eyebrow="FINANCE / WORKFLOW" title="Requests & approvals" description="Financial requests route to the CEO; other requests follow their selected approval role." action={<><button className="button secondary" onClick={() => onToast("Workflow rules opened") }><Wrench size={16} /> Configure workflows</button><button className="button primary" onClick={() => openModal("request")}><Plus size={16} /> New request</button></>} />
    <div className="request-layout">
      <section className="card request-inbox">
        <div className="request-summary"><div><span>Open approval queue</span><strong>{pending.length}</strong><small>Requests waiting on your role</small></div><div className="request-ring"><span>75%</span><small>within SLA</small></div></div>
        <div className="request-filters"><button className="active">All <b>{requests.length}</b></button><button>Expenses <b>{requests.filter((item) => item.requestType === "Expense").length}</b></button><button>Leave <b>{requests.filter((item) => item.requestType === "Leave").length}</b></button><button>Other <b>{requests.filter((item) => !["Expense", "Leave"].includes(item.requestType)).length}</b></button></div>
        {requests.map((item) => {
          const financial = isFinancialRequest(item);
          const requiredRole = financial ? "CEO" : item.requiredRole;
          const canDecide = role === requiredRole || (!financial && role === "Organization Admin");
          return <div className="request-row" key={item.id}>
            <span className={`request-type ${item.requestType.toLowerCase()}`}><FileCheck2 size={16} /></span>
            <div className="request-copy"><div><strong>{item.title}</strong><Status value={item.status} /></div><span>{item.requestType} · {item.requester} · {item.createdAt}{item.details ? ` · ${item.details}` : ""}</span></div>
            {typeof item.amount === "number" && <strong className="request-amount">{naira(item.amount)}</strong>}
            {item.status === "pending" ? canDecide ? <div className="request-actions"><button className="approve-button" aria-label={`Approve ${item.title}`} onClick={() => reviewRequest(item, "approved")}><Check size={14} /></button><button className="reject-button" aria-label={`Reject ${item.title}`} onClick={() => reviewRequest(item, "rejected")}><X size={14} /></button></div> : <span className="request-amount">Awaiting {requiredRole}</span> : <button className="icon-button" onClick={() => onToast("Request history opened")}><MoreHorizontal size={17} /></button>}
          </div>;
        })}
      </section>
      <aside className="card workflow-card"><OpsCardHeading title="Approval policy" subtitle="Financial requests of every value" /><div className="workflow-steps"><div><span>1</span><div><strong>Requester</strong><small>Submit supporting details</small></div></div><i></i><div><span>2</span><div><strong>CEO</strong><small>Final approval required</small></div></div><i></i><div><span>3</span><div><strong>Audit trail</strong><small>Record the decision</small></div></div></div><div className="workflow-note"><ShieldCheck size={15} /><span>Finance teams may prepare records; the CEO approves every financial request.</span></div></aside>
    </div>
  </>;
}

function AssetsPage({ assets, onToast, openModal }: SharedProps) { const counts = { all: assets.length, assigned: assets.filter((item) => item.status === "assigned").length, available: assets.filter((item) => item.status === "available").length, maintenance: assets.filter((item) => item.status === "maintenance").length }; return <><OpsHeader eyebrow="OPERATIONS / ASSETS" title="Asset register" description="Know what the business owns, where it is and who is accountable." action={<button className="button primary" onClick={() => openModal("asset")}><Plus size={16} /> Add asset</button>} /><div className="asset-summary"><div className="asset-value"><span>Total book value</span><strong>₦8.4m</strong><small>142 tracked assets</small></div><div className="asset-counts">{[["All assets", counts.all], ["Assigned", counts.assigned], ["Available", counts.available], ["Maintenance", counts.maintenance]].map(([label, count]) => <div key={String(label)}><strong>{count}</strong><span>{label}</span></div>)}</div></div><section className="card table-card"><OpsTableToolbar placeholder="Search by asset, tag or serial number" action={<button className="filter-button"><Filter size={14} /> Categories <ChevronDown size={14} /></button>} /><div className="table-scroll"><table><thead><tr><th>Asset</th><th>Category</th><th>Assigned to</th><th>Location</th><th>Value</th><th>Status</th><th></th></tr></thead><tbody>{assets.map((item) => <tr key={item.id}><td><div className="employee-cell"><span className="asset-mini-icon"><Laptop size={16} /></span><div><strong>{item.name}</strong><span>{item.assetTag} · {item.serialNumber}</span></div></div></td><td>{item.category}</td><td>{item.assignee || "Unassigned"}</td><td><span className="location-pill"><MapPin size={12} />{item.location}</span></td><td>{naira(item.value)}</td><td><Status value={item.status} /></td><td><button className="icon-button" onClick={() => onToast(`Asset history opened for ${item.assetTag}`)}><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table></div></section></> }

function VendorsPage({ vendors, onToast, openModal }: SharedProps) { return <><OpsHeader eyebrow="OPERATIONS / VENDORS" title="Vendors" description="Manage vendor relationships, contracts and renewal risk in one place." action={<button className="button primary" onClick={() => openModal("vendor")}><Plus size={16} /> Add vendor</button>} /><div className="vendor-callout"><div className="vendor-callout-icon"><AlertCircle size={18} /></div><div><strong>1 contract needs attention</strong><span>Cedar People Partners expires on 15 October 2026.</span></div><button onClick={() => onToast("Renewal workspace opened")}>Review renewals <ArrowUpRight size={14} /></button></div><section className="card table-card"><OpsTableToolbar placeholder="Search vendors, contacts or services" action={<button className="filter-button"><Filter size={14} /> All statuses <ChevronDown size={14} /></button>} /><div className="table-scroll"><table><thead><tr><th>Vendor</th><th>Service</th><th>Primary contact</th><th>Contract end</th><th>Spend</th><th>Status</th><th></th></tr></thead><tbody>{vendors.map((vendor) => <tr key={vendor.id}><td><div className="vendor-cell"><span className="vendor-avatar">{vendor.name.split(" ").map((word) => word[0]).slice(0, 2).join("")}</span><div><strong>{vendor.name}</strong><span>{vendor.email}</span></div></div></td><td>{vendor.category}</td><td>{vendor.contactName}</td><td>{vendor.contractEnd}</td><td><strong>{compactNaira(vendor.spend)}</strong></td><td><Status value={vendor.status} /></td><td><button className="text-button" onClick={() => onToast("Vendor profile opened")}>View</button></td></tr>)}</tbody></table></div></section></> }

function HelpdeskPage({ tickets, onToast, openModal }: SharedProps) { return <><OpsHeader eyebrow="OPERATIONS / HELPDESK" title="Helpdesk" description="Give every internal request a clear owner, SLA and resolution path." action={<button className="button primary" onClick={() => openModal("ticket")}><Plus size={16} /> New ticket</button>} /><div className="ops-stat-grid"><OpsStat icon={LifeBuoy} tone="blue" label="Open tickets" value="18" detail="Across all categories" /><OpsStat icon={Clock3} tone="orange" label="Due this week" value="7" detail="Within SLA" /><OpsStat icon={TicketCheck} tone="green" label="Resolved this month" value="64" detail="92% satisfaction" /><OpsStat icon={Users} tone="violet" label="Assigned to me" value="4" detail="Needs attention" /></div><section className="card table-card"><OpsTableToolbar placeholder="Search ticket number or subject" action={<button className="filter-button"><Filter size={14} /> All categories <ChevronDown size={14} /></button>} /><div className="table-scroll"><table><thead><tr><th>Ticket</th><th>Category</th><th>Requester</th><th>Assignee</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>{tickets.map((ticket) => <tr key={ticket.id}><td><div><strong className="table-primary">{ticket.subject}</strong><span className="table-secondary">{ticket.ticketNumber} · {ticket.createdAt}</span></div></td><td>{ticket.category}</td><td>{ticket.requester}</td><td>{ticket.assignee || "Unassigned"}</td><td><span className={`priority ${ticket.priority}`}>{ticket.priority}</span></td><td><Status value={ticket.status} /></td><td><button className="text-button" onClick={() => onToast(`Ticket ${ticket.ticketNumber} opened`)}>Open</button></td></tr>)}</tbody></table></div></section></> }

function CalendarPage({ events, onToast }: SharedProps) { return <><OpsHeader eyebrow="WORK / CALENDAR" title="Business calendar" description="Bring leave, meetings, training and deadlines into a shared view." action={<button className="button primary" onClick={() => onToast("Calendar event composer opened")}><Plus size={16} /> Add event</button>} /><div className="calendar-shell"><section className="card calendar-main"><div className="calendar-top"><div><OpsCardHeading title="September 2026" subtitle="All organization events" /></div><div className="calendar-switch"><button>‹</button><button className="today">Today</button><button>›</button></div></div><div className="calendar-grid-head">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: 35 }, (_, index) => { const day = index - 3; const active = day > 0 && day <= 30; const event = day === 28 ? events[0] : day === 29 ? events[2] : null; return <div className={`calendar-cell ${day === 28 ? "today-cell" : ""}`} key={index}>{active && <><span className="calendar-date">{day}</span>{event && <button className={`calendar-event ${event.eventType.toLowerCase()}`} onClick={() => onToast(event.title)}>{event.title}</button>}{day === 30 && <button className="calendar-event leave" onClick={() => onToast("Leave calendar opened")}>Nneka on leave</button>}</>}</div>; })}</div></section><aside className="card upcoming-card"><OpsCardHeading title="Upcoming" subtitle="Next events across Zyntris" /><div className="upcoming-list">{events.map((event) => <button key={event.id} onClick={() => onToast(event.title)}><span className={`upcoming-date ${event.eventType.toLowerCase()}`}><strong>{event.startAt === "All day" ? "—" : event.startAt}</strong><small>{event.eventType}</small></span><span><strong>{event.title}</strong><small>{event.location || event.owner}</small></span><ArrowUpRight size={14} /></button>)}</div><div className="calendar-note"><CalendarDays size={15} /><span>Connect Google or Outlook Calendar from Administration.</span></div></aside></div></> }

function CustomersPage({ customers, onToast, openModal }: SharedProps) { const stages = ["lead", "qualified", "proposal", "negotiation", "won"]; return <><OpsHeader eyebrow="CUSTOMERS / CRM" title="Customer pipeline" description="Keep the customer story connected from first conversation to renewal." action={<button className="button primary" onClick={() => openModal("customer")}><Plus size={16} /> Add customer</button>} /><div className="crm-summary"><div><span>Pipeline value</span><strong>{compactNaira(customers.reduce((sum, item) => sum + item.value, 0))}</strong><small>Across active opportunities</small></div><div><span>Won this quarter</span><strong>₦7.6m</strong><small>1 customer closed</small></div><div><span>Open opportunities</span><strong>{customers.filter((item) => !["won", "lost"].includes(item.stage)).length}</strong><small>Need next activity</small></div></div><section className="card crm-board"><div className="kanban-header"><div><h2>Opportunity pipeline</h2><p>Drag-ready stages for a focused sales rhythm.</p></div><button className="filter-button"><Filter size={14} /> This quarter <ChevronDown size={14} /></button></div><div className="crm-columns">{stages.map((stage) => <div className="crm-column" key={stage}><div className="column-title"><span><i className={`column-dot ${stage}`}></i>{titleCase(stage)}</span><b>{customers.filter((item) => item.stage === stage).length}</b></div>{customers.filter((item) => item.stage === stage).map((customer) => <button className="crm-card" key={customer.id} onClick={() => onToast(`${customer.company || customer.name} profile opened`)}><div className="crm-avatar">{customer.name.split(" ").map((word) => word[0]).join("")}</div><strong>{customer.company || customer.name}</strong><span>{customer.name} · {compactNaira(customer.value)}</span><small>{customer.lastActivity}</small></button>)}</div>)}</div></section></> }

function BudgetsPage({ onToast }: { onToast: (message: string) => void }) { const rows = [{ name: "People & culture", category: "People", allocated: 12000000, spent: 7600000, status: "on track" }, { name: "Technology operations", category: "Technology", allocated: 28000000, spent: 22400000, status: "watch" }, { name: "Customer growth", category: "Sales & Marketing", allocated: 18000000, spent: 9200000, status: "on track" }]; return <><OpsHeader eyebrow="FINANCE / BUDGETS" title="Budgets" description="Make planned spend visible before it becomes a surprise." action={<button className="button primary" onClick={() => onToast("Budget composer opened")}><Plus size={16} /> Create budget</button>} /><div className="ops-stat-grid"><OpsStat icon={WalletCards} tone="blue" label="Total allocated" value="₦58m" detail="Q4 2026" /><OpsStat icon={CircleDollarSign} tone="orange" label="Committed" value="₦39.2m" detail="67.6% utilized" /><OpsStat icon={ShieldCheck} tone="green" label="On track" value="2 of 3" detail="Budgets within plan" /><OpsStat icon={AlertCircle} tone="violet" label="Watch list" value="1" detail="Technology operations" /></div><section className="card budget-list"><OpsCardHeading title="Budget performance" subtitle="Quarterly allocation versus actual spend" />{rows.map((row) => <div className="budget-row" key={row.name}><div className="budget-title"><span className="budget-icon"><WalletCards size={16} /></span><div><strong>{row.name}</strong><small>{row.category}</small></div></div><div className="budget-progress"><div><i className={row.status === "watch" ? "watch" : ""} style={{ width: `${Math.round((row.spent / row.allocated) * 100)}%` }}></i></div><span>{Math.round((row.spent / row.allocated) * 100)}%</span></div><div className="budget-numbers"><strong>{compactNaira(row.spent)}</strong><span>of {compactNaira(row.allocated)}</span></div><Status value={row.status} /></div>)}</section></> }

function OpsModal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="modal"><div className="modal-header"><div><div className="eyebrow">ZYNTRIS OPERATIONS</div><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div>{children}</div></div>; }
